### ISSUE TITLE
Helmwave build don't work on different k8s cluster 

### ISSUE THREAD

**Issue by GlitchTQ** [helmwave/argocd-plugin#1]
When ArgoCD application created for different k8s cluster, we get accesses error for serviceAccount.
Similar error arise when target cluster is unavailable 
Because we just need to generate manifests for k8s, we need to run `helmwave build` without connecting to cluster, 
how we can achieve this?

**Comment by zhilyaev** [comment]
https://docs.helmwave.app/0.41.x/examples/private-env/

https://docs.helmwave.app/0.41.x/yaml/?h=offl#offline_kube_version

**Comment by GlitchTQ** [comment]
Solution for this issue is add `--diff-mode=none` for helmwave command and add `offline_kube_version` option in `helmwave.yml`
```yml
releases:
    - name: someApp
      offline_kube_version: 1.27.0
```

**Comment by GlitchTQ** [comment]
Solution for this issue is add `--diff-mode=none` for helmwave command and add `offline_kube_version` option in `helmwave.yml`
```yml
releases:
    - name: someApp
      offline_kube_version: 1.27.0
```
